export const DesktopNavMenu = () => {
  return (
    <ul className="box-content caret-black block justify-normal list-disc max-w-none pl-10 md:aspect-auto md:box-border md:caret-transparent md:flex md:justify-end md:list-none md:max-w-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pl-0 md:scroll-m-0 md:scroll-p-[auto]">
      <li className="text-base font-normal [align-items:normal] box-content caret-black list-item tracking-[normal] leading-[normal] min-h-0 min-w-0 normal-case text-wrap md:font-semibold md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:tracking-[2px] md:leading-[30px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:uppercase md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></li>
      <li className="static text-base font-normal [align-items:normal] box-content caret-black list-item tracking-[normal] leading-[normal] min-h-0 min-w-0 normal-case text-wrap ml-0 md:relative md:font-semibold md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:tracking-[2px] md:leading-[30px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:uppercase md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:ml-[35px] md:scroll-m-0 md:scroll-p-[auto]"></li>
      <li className="text-base font-normal [align-items:normal] box-content caret-black list-item tracking-[normal] leading-[normal] min-h-0 min-w-0 normal-case text-wrap ml-0 md:font-semibold md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:tracking-[2px] md:leading-[30px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:uppercase md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:ml-[35px] md:scroll-m-0 md:scroll-p-[auto]"></li>
      <li className="static text-base font-normal [align-items:normal] box-content caret-black list-item tracking-[normal] leading-[normal] min-h-0 min-w-0 normal-case text-wrap ml-0 md:relative md:font-semibold md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:tracking-[2px] md:leading-[30px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:uppercase md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:ml-[35px] md:scroll-m-0 md:scroll-p-[auto]"></li>
      <li className="static text-base font-normal [align-items:normal] box-content caret-black list-item tracking-[normal] leading-[normal] min-h-0 min-w-0 normal-case text-wrap ml-0 md:relative md:font-semibold md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:tracking-[2px] md:leading-[30px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:uppercase md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:ml-[35px] md:scroll-m-0 md:scroll-p-[auto]"></li>
      <li className="text-base font-normal [align-items:normal] box-content caret-black list-item tracking-[normal] leading-[normal] min-h-0 min-w-0 normal-case text-wrap ml-0 md:font-semibold md:items-center md:aspect-auto md:box-border md:caret-transparent md:flex md:tracking-[2px] md:leading-[30px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:uppercase md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:ml-[35px] md:scroll-m-0 md:scroll-p-[auto]">
        <div className="text-black text-base box-content caret-black tracking-[normal] min-h-0 min-w-0 text-wrap md:text-white md:text-[15px] md:aspect-auto md:box-border md:caret-transparent md:tracking-[1px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] hover:underline">
          More
        </div>
        <div className="static bg-transparent box-content caret-black opacity-100 text-wrap visible w-auto p-0 left-auto top-auto md:absolute md:aspect-auto md:bg-stone-500 md:box-border md:caret-transparent md:opacity-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:invisible md:w-full md:[mask-position:0%] md:bg-left-top md:px-[50px] md:py-5 md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:top-full">
          <div className="box-content caret-black max-w-none text-wrap w-auto mx-0 md:aspect-auto md:box-border md:caret-transparent md:max-w-[1200px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-full md:[mask-position:0%] md:bg-left-top md:mx-auto md:scroll-m-0 md:scroll-p-[auto]">
            <div className="box-content caret-black block flex-nowrap text-start text-wrap w-auto md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-wrap md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:underline-offset-auto md:text-nowrap md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              <div className="box-content caret-black max-w-none min-h-0 min-w-0 text-wrap align-baseline w-auto mx-0 pr-0 md:aspect-auto md:box-border md:caret-transparent md:max-w-full md:min-h-px md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-top md:w-3/12 md:[mask-position:0%] md:bg-left-top md:mx-auto md:pr-10 md:scroll-m-0 md:scroll-p-[auto]"></div>
              <div className="box-content caret-black max-w-none min-h-0 min-w-0 text-wrap align-baseline w-auto mx-0 pr-0 md:aspect-auto md:box-border md:caret-transparent md:max-w-full md:min-h-px md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-top md:w-3/12 md:[mask-position:0%] md:bg-left-top md:mx-auto md:pr-10 md:scroll-m-0 md:scroll-p-[auto]"></div>
              <div className="box-content caret-black max-w-none min-h-0 min-w-0 text-wrap align-baseline w-auto mx-0 pr-0 md:aspect-auto md:box-border md:caret-transparent md:max-w-full md:min-h-px md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-top md:w-3/12 md:[mask-position:0%] md:bg-left-top md:mx-auto md:pr-10 md:scroll-m-0 md:scroll-p-[auto]"></div>
              <div className="box-content caret-black max-w-none min-h-0 min-w-0 text-wrap align-baseline w-auto mx-0 pr-0 md:aspect-auto md:box-border md:caret-transparent md:max-w-full md:min-h-px md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-top md:w-3/12 md:[mask-position:0%] md:bg-left-top md:mx-auto md:pr-10 md:scroll-m-0 md:scroll-p-[auto]"></div>
              <div className="box-content caret-black max-w-none min-h-0 min-w-0 text-wrap align-baseline w-auto mx-0 pr-0 md:aspect-auto md:box-border md:caret-transparent md:max-w-full md:min-h-px md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:align-top md:w-3/12 md:[mask-position:0%] md:bg-left-top md:mx-auto md:pr-10 md:scroll-m-0 md:scroll-p-[auto]"></div>
            </div>
          </div>
        </div>
      </li>
    </ul>
  );
};
